language: android

node_js:
  - 8.12
npm:
  - 6.4.1
notifications:
  email: false

sudo: true

branches:
  only:
  - master

install:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
  - sudo apt install nodejs
  - sudo npm install -g cordova
  - npm install
  - echo y | android update sdk -u --filter android-22,android-23

before_script:
  - cordova platform rm android
  - cordova platform add android

script:
  - cordova prepare
  - cordova build android --release -- --ant
  
release:
  - exit 0  